name: Promote to QA
on:
  push:
    branches-ignore: 
      dev

jobs:
  build-and-promote:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install all dependencies
      run: composer install

    - name: SSH Deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SOURCE: "/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
